# NUMPY

In [2]:
import numpy as np
import random
import math

In [2]:
# 1) Create a 1D NumPy array of numbers from 10 to 50.

In [3]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [4]:
# 2) Create a 3×3 identity matrix using NumPy.

In [5]:
arr = np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# 3) Reshape a 1D array of numbers 1–12 into a 3×4 matrix.

In [8]:
arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
# 4) Find the mean, median, and standard deviation of a NumPy array.

In [15]:
arr = np.arange(1,11)
print("Array : ", arr)
print("Mean of the array : ", np.mean(arr))
print("Median of the array : ", np.median(arr))
print("Standard Deviation of the array : ", np.std(arr))


Array :  [ 1  2  3  4  5  6  7  8  9 10]
Mean of the array :  5.5
Median of the array :  5.5
Standard Deviation of the array :  2.8722813232690143


In [16]:
# 5) Add two NumPy arrays element-wise and compare speeds vs Python lists.

In [29]:
import timeit

In [33]:
arr1 = np.array([1,1,1,1,1,1])
arr2 = np.array([11,22,33,44,55,66])
print("time to evaluate addition of two numpy arrays : ")
%timeit [arr1 + arr2]

print()
lst1 = [1,1,1,1,1,1]
lst2 = [11,22,33,44,55,66]
print("time to evaluate addition of two lists : ")
%timeit [lst1 + lst2]

time to evaluate addition of two numpy arrays : 
1.6 μs ± 101 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

time to evaluate addition of two lists : 
265 ns ± 4.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [34]:
# 6) Slice: extract 2nd row & 3rd column from a 4×4 matrix.

In [42]:
arr = np.arange(1,17).reshape(4,4)
print("4*4 matrix : ")
print(arr)
print()

print("2nd row : ", arr[1,:])
print("3rd column : ", arr[: , 2])

4*4 matrix : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

2nd row :  [5 6 7 8]
3rd column :  [ 3  7 11 15]


In [43]:
# 7) Stack two arrays vertically and horizontally.

In [50]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(11,23).reshape(3,4)
print("Array 1 :")
print(arr1)
print()
print("Array 2 :")
print(arr2)
print()

print("Horizontal stacking :")
print(np.hstack((arr1,arr2)))
print()

print("Vertical stacking :")
print(np.vstack((arr1,arr2)))

Array 1 :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array 2 :
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]

Horizontal stacking :
[[ 1  2  3  4 11 12 13 14]
 [ 5  6  7  8 15 16 17 18]
 [ 9 10 11 12 19 20 21 22]]

Vertical stacking :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [51]:
# 8) Generate 10 random integers between 1–100.

In [52]:
print(np.random.randint(1,100,10))

[43  1 15 64 73 64 41 72 25 39]


In [53]:
# 9) Replace all elements < 5 with 0 in a NumPy array.

In [59]:
arr = np.random.randint(1,10,9).reshape(3,3)
print("Array : ")
print(arr)
print()

for i in range(3):
    for j in range (3):
        if arr[i][j] < 5 :
            arr[i][j] = 0
print("Replace all elements less then 5 with 0 :")
print(arr)

Array : 
[[2 7 4]
 [6 9 9]
 [4 7 4]]

Replace all elements less then 5 with 0 :
[[0 7 0]
 [6 9 9]
 [0 7 0]]


In [54]:
# 10) Multiply each row of a matrix by a different number.

In [67]:
arr = np.ones((4,4))
print("Array : ")
print(arr)
print()

n = 3
for i in range(4):
    for j in range (4):      
        arr[i][j] = arr[i][j] * n
    n = n+1    

print("Multiply each row of a matrix by a different number :")
print(arr)

Array : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Multiply each row of a matrix by a different number :
[[3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]]


# PANDAS

In [3]:
import pandas as pd

In [11]:
# 1) Load a CSV file and display first 10 rows.

In [62]:
dt = pd.read_csv(r"students_data.csv")
data = pd.DataFrame(dt)
data.head(10)

ID       Name  Age  Marks     Sex
0  S001   Student1   19     84  Female
1  S002   Student2   24     86  Female
2  S003   Student3   20     68    Male
3  S004   Student4   21     98  Female
4  S005   Student5   23     89  Female
5  S006   Student6   18     95  Female
6  S007   Student7   21     73  Female
7  S008   Student8   21     51  Female
8  S009   Student9   20     85    Male
9  S010  Student10   22     73  Female

In [ ]:
# 2) Create a Pandas DataFrame of students (name, age, marks).

In [40]:
data = { 'id'   : range(101,111),
         'Name' : ['Max','Neon','Alex','Hard',"Amit", "Neha", "Rohit", "Priya", "Kunal", "Simran"] , 
         'Age'  : [25, 26, 24, 23, 20, 21, None, 20, 23, 21] , 
         'Marks': [95, 98, None, 85, 78, 82, None, 67, 73, 88]
       }
dt = pd.DataFrame(data)
dt

id    Name   Age  Marks
0  101     Max  25.0   95.0
1  102    Neon  26.0   98.0
2  103    Alex  24.0    NaN
3  104    Hard  23.0   85.0
4  105    Amit  20.0   78.0
5  106    Neha  21.0   82.0
6  107   Rohit   NaN    NaN
7  108   Priya  20.0   67.0
8  109   Kunal  23.0   73.0
9  110  Simran  21.0   88.0

In [38]:
# 3) Check for missing values and fill them with mean.

In [41]:
df = dt
df.isnull().any()

id       False
Name     False
Age       True
Marks     True
dtype: bool

In [43]:
df2 = df.fillna(df.mean(numeric_only = True))
df2

id    Name        Age  Marks
0  101     Max  25.000000  95.00
1  102    Neon  26.000000  98.00
2  103    Alex  24.000000  83.25
3  104    Hard  23.000000  85.00
4  105    Amit  20.000000  78.00
5  106    Neha  21.000000  82.00
6  107   Rohit  22.555556  83.25
7  108   Priya  20.000000  67.00
8  109   Kunal  23.000000  73.00
9  110  Simran  21.000000  88.00

In [44]:
# 4) Remove rows where marks < 80.

In [47]:
df3 = df2[df2['Marks']>80]
df3

id    Name        Age  Marks
0  101     Max  25.000000  95.00
1  102    Neon  26.000000  98.00
2  103    Alex  24.000000  83.25
3  104    Hard  23.000000  85.00
5  106    Neha  21.000000  82.00
6  107   Rohit  22.555556  83.25
9  110  Simran  21.000000  88.00

In [48]:
df4 = df2[df2['Marks']>80].reset_index(drop=True)
df4

id    Name        Age  Marks
0  101     Max  25.000000  95.00
1  102    Neon  26.000000  98.00
2  103    Alex  24.000000  83.25
3  104    Hard  23.000000  85.00
4  106    Neha  21.000000  82.00
5  107   Rohit  22.555556  83.25
6  110  Simran  21.000000  88.00

In [50]:
df2['Sex'] = ['male','male','male','female','male','female','male','female','male','female',]
df2

id    Name        Age  Marks     Sex
0  101     Max  25.000000  95.00    male
1  102    Neon  26.000000  98.00    male
2  103    Alex  24.000000  83.25    male
3  104    Hard  23.000000  85.00  female
4  105    Amit  20.000000  78.00    male
5  106    Neha  21.000000  82.00  female
6  107   Rohit  22.555556  83.25    male
7  108   Priya  20.000000  67.00  female
8  109   Kunal  23.000000  73.00    male
9  110  Simran  21.000000  88.00  female

In [49]:
# 5) Group a DataFrame by “sex” and calculate average marks.

In [52]:
result = df2.groupby('Sex')['Marks'].mean()
print(result)

Sex
female    80.500000
male      85.083333
Name: Marks, dtype: float64


In [53]:
# 6) Sort a DataFrame by age descending.

In [55]:
result = df2.sort_values(by='Age', ascending=False)
result

id    Name        Age  Marks     Sex
1  102    Neon  26.000000  98.00    male
0  101     Max  25.000000  95.00    male
2  103    Alex  24.000000  83.25    male
3  104    Hard  23.000000  85.00  female
8  109   Kunal  23.000000  73.00    male
6  107   Rohit  22.555556  83.25    male
5  106    Neha  21.000000  82.00  female
9  110  Simran  21.000000  88.00  female
4  105    Amit  20.000000  78.00    male
7  108   Priya  20.000000  67.00  female

In [56]:
# by marks
result = df2.sort_values(by='Marks', ascending=False)
result

id    Name        Age  Marks     Sex
1  102    Neon  26.000000  98.00    male
0  101     Max  25.000000  95.00    male
9  110  Simran  21.000000  88.00  female
3  104    Hard  23.000000  85.00  female
2  103    Alex  24.000000  83.25    male
6  107   Rohit  22.555556  83.25    male
5  106    Neha  21.000000  82.00  female
4  105    Amit  20.000000  78.00    male
8  109   Kunal  23.000000  73.00    male
7  108   Priya  20.000000  67.00  female

In [58]:
new_df = df2
new_df

id    Name        Age  Marks     Sex
0  101     Max  25.000000  95.00    male
1  102    Neon  26.000000  98.00    male
2  103    Alex  24.000000  83.25    male
3  104    Hard  23.000000  85.00  female
4  105    Amit  20.000000  78.00    male
5  106    Neha  21.000000  82.00  female
6  107   Rohit  22.555556  83.25    male
7  108   Priya  20.000000  67.00  female
8  109   Kunal  23.000000  73.00    male
9  110  Simran  21.000000  88.00  female

In [57]:
# 7) Add a new column “Grade” based on marks conditions.

In [59]:
def get_grade(m):
    if m >= 90:
        return "A"
    elif m >= 80:
        return "B"
    elif m >= 70:
        return "C"
    else:
        return "D"

new_df['Grade'] =  new_df['Marks'].apply(get_grade)     
new_df

id    Name        Age  Marks     Sex Grade
0  101     Max  25.000000  95.00    male     A
1  102    Neon  26.000000  98.00    male     A
2  103    Alex  24.000000  83.25    male     B
3  104    Hard  23.000000  85.00  female     B
4  105    Amit  20.000000  78.00    male     C
5  106    Neha  21.000000  82.00  female     B
6  107   Rohit  22.555556  83.25    male     B
7  108   Priya  20.000000  67.00  female     D
8  109   Kunal  23.000000  73.00    male     C
9  110  Simran  21.000000  88.00  female     B

In [60]:
# 8) Merge two DataFrames .

In [63]:
d1 = data.head(10)
print(d1)
d2 = df2
print(df2)

     ID       Name  Age  Marks     Sex
0  S001   Student1   19     84  Female
1  S002   Student2   24     86  Female
2  S003   Student3   20     68    Male
3  S004   Student4   21     98  Female
4  S005   Student5   23     89  Female
5  S006   Student6   18     95  Female
6  S007   Student7   21     73  Female
7  S008   Student8   21     51  Female
8  S009   Student9   20     85    Male
9  S010  Student10   22     73  Female
    id    Name        Age  Marks     Sex Grade
0  101     Max  25.000000  95.00    male     A
1  102    Neon  26.000000  98.00    male     A
2  103    Alex  24.000000  83.25    male     B
3  104    Hard  23.000000  85.00  female     B
4  105    Amit  20.000000  78.00    male     C
5  106    Neha  21.000000  82.00  female     B
6  107   Rohit  22.555556  83.25    male     B
7  108   Priya  20.000000  67.00  female     D
8  109   Kunal  23.000000  73.00    male     C
9  110  Simran  21.000000  88.00  female     B


In [65]:
new = pd.merge(d1, d2, on='Sex', how='outer')
new

ID     Name_x  Age_x  Marks_x     Sex     id  Name_y      Age_y  \
0   S001   Student1   19.0     84.0  Female    NaN     NaN        NaN   
1   S002   Student2   24.0     86.0  Female    NaN     NaN        NaN   
2   S004   Student4   21.0     98.0  Female    NaN     NaN        NaN   
3   S005   Student5   23.0     89.0  Female    NaN     NaN        NaN   
4   S006   Student6   18.0     95.0  Female    NaN     NaN        NaN   
5   S007   Student7   21.0     73.0  Female    NaN     NaN        NaN   
6   S008   Student8   21.0     51.0  Female    NaN     NaN        NaN   
7   S010  Student10   22.0     73.0  Female    NaN     NaN        NaN   
8   S003   Student3   20.0     68.0    Male    NaN     NaN        NaN   
9   S009   Student9   20.0     85.0    Male    NaN     NaN        NaN   
10   NaN        NaN    NaN      NaN  female  104.0    Hard  23.000000   
11   NaN        NaN    NaN      NaN  female  106.0    Neha  21.000000   
12   NaN        NaN    NaN      NaN  female  108.0   Priya  20.000000   
13   NaN        NaN    NaN      NaN  female  110.0  Simran  21.000000   
14   NaN        NaN    NaN      NaN    male  101.0     Max  25.000000   
15   NaN        NaN    NaN      NaN    male  102.0    Neon  26.000000   
16   NaN        NaN    NaN      NaN    male  103.0    Alex  24.000000   
17   NaN        NaN    NaN      NaN    male  105.0    Amit  20.000000   
18   NaN        NaN    NaN      NaN    male  107.0   Rohit  22.555556   
19   NaN        NaN    NaN      NaN    male  109.0   Kunal  23.000000   

    Marks_y Grade  
0       NaN   NaN  
1       NaN   NaN  
2       NaN   NaN  
3       NaN   NaN  
4       NaN   NaN  
5       NaN   NaN  
6       NaN   NaN  
7       NaN   NaN  
8       NaN   NaN  
9       NaN   NaN  
10    85.00     B  
11    82.00     B  
12    67.00     D  
13    88.00     B  
14    95.00     A  
15    98.00     A  
16    83.25     B  
17    78.00     C  
18    83.25     B  
19    73.00     C

In [66]:
# 9)  Find the top 5 highest values in a column.

In [67]:
# whole rows
df2.nlargest(5, 'Marks')

id    Name   Age  Marks     Sex Grade
1  102    Neon  26.0  98.00    male     A
0  101     Max  25.0  95.00    male     A
9  110  Simran  21.0  88.00  female     B
3  104    Hard  23.0  85.00  female     B
2  103    Alex  24.0  83.25    male     B

In [68]:
# only values
df2['Marks'].nlargest(5)

1    98.00
0    95.00
9    88.00
3    85.00
2    83.25
Name: Marks, dtype: float64

In [69]:
res = df2.sort_values(by='Marks', ascending=False)
res.head(5)

id    Name   Age  Marks     Sex Grade
1  102    Neon  26.0  98.00    male     A
0  101     Max  25.0  95.00    male     A
9  110  Simran  21.0  88.00  female     B
3  104    Hard  23.0  85.00  female     B
2  103    Alex  24.0  83.25    male     B

In [70]:
# 10) Convert a column to datetime and extract year, month and day.

In [75]:
data = { 'Date': ['2023-01-15', '2022-07-10', '2024-03-25'] }

df = pd.DataFrame(data)
df

Date
0  2023-01-15
1  2022-07-10
2  2024-03-25

In [76]:
# Convert to datetime
df['Date'] = pd.to_datetime(df['Date'], format="%Y-%m-%d")          # if there's like 2023/01/15 - "%Y/%m/%d"
df                                                                  # if there's like 2023/january/15 - "%Y/%b/%d" (use b instead of m)           

Date
0 2023-01-15
1 2022-07-10
2 2024-03-25

In [77]:
# Extract year and month and day
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day
df

Date  year  month  day
0 2023-01-15  2023      1   15
1 2022-07-10  2022      7   10
2 2024-03-25  2024      3   25

In [1]:
# 11) Replace similar string data in a column 

In [20]:
data = {
    'id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    'age': [23, 45, 31, 29, 40, 36, 22, 27, 33, 41],
    'marks': [78, 85, 90, 67, 72, 88, 95, 60, 82, 77],
    'target': ['cat', 'dog', 'fish', 'cat', 'dog', 'fish', 'cat', 'dog', 'fish', 'cat']
}
df = pd.DataFrame(data)
df1 = df
df

id name  age  marks target
0   1    A   23     78    cat
1   2    B   45     85    dog
2   3    C   31     90   fish
3   4    D   29     67    cat
4   5    E   40     72    dog
5   6    F   36     88   fish
6   7    G   22     95    cat
7   8    H   27     60    dog
8   9    I   33     82   fish
9  10    J   41     77    cat

In [21]:
df['target'].count()

np.int64(10)

In [22]:
df['target'].unique()

array(['cat', 'dog', 'fish'], dtype=object)

In [23]:
df['target'] = df['target'].replace({'cat':0, 'dog':1, 'fish':2})
df
# pd.set_option('future.no_silent_downcasting', True) if got any warning

id name  age  marks target
0   1    A   23     78      0
1   2    B   45     85      1
2   3    C   31     90      2
3   4    D   29     67      0
4   5    E   40     72      1
5   6    F   36     88      2
6   7    G   22     95      0
7   8    H   27     60      1
8   9    I   33     82      2
9  10    J   41     77      0

In [24]:
df['target'].unique()

array([0, 1, 2], dtype=object)

In [25]:
df.dtypes


id         int64
name      object
age        int64
marks      int64
target    object
dtype: object

In [26]:
# 2nd option by "ONE HOT Encoding"
df2 = pd.get_dummies(df1, columns=['target'])
df2

id name  age  marks  target_0  target_1  target_2
0   1    A   23     78      True     False     False
1   2    B   45     85     False      True     False
2   3    C   31     90     False     False      True
3   4    D   29     67      True     False     False
4   5    E   40     72     False      True     False
5   6    F   36     88     False     False      True
6   7    G   22     95      True     False     False
7   8    H   27     60     False      True     False
8   9    I   33     82     False     False      True
9  10    J   41     77      True     False     False

In [27]:
# 3rd option by Label encoding

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df1['target'] = le.fit_transform(df1['target'])
df1

id name  age  marks  target
0   1    A   23     78       0
1   2    B   45     85       1
2   3    C   31     90       2
3   4    D   29     67       0
4   5    E   40     72       1
5   6    F   36     88       2
6   7    G   22     95       0
7   8    H   27     60       1
8   9    I   33     82       2
9  10    J   41     77       0